spring:
  application:
    name: Mtprototest

  datasource:
    url: jdbc:postgresql://localhost:5432/mtproto_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
app:
  parser:
    fixed-delay-ms: 43200000

  sources:
    solispirit:
      url: https://raw.githubusercontent.com/SoliSpirit/mtproto/master/all_proxies.txt